package Vistas;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class PQR extends javax.swing.JFrame
{

	/**
	 * Creates new form PQR
	 */
	public PQR()
	{
		initComponents();

		this.getContentPane().setBackground(Color.white);
	}
        
        public String inputdialog(String texto){
	   String palabra = JOptionPane.showInputDialog(texto);
	   return palabra;
        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPQR = new javax.swing.JTextArea();
        reportUser = new javax.swing.JButton();
        sendPDF = new javax.swing.JButton();
        pqrType = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPQR.setEditable(false);
        panelPQR.setBackground(new java.awt.Color(252, 252, 252));
        panelPQR.setColumns(20);
        panelPQR.setRows(5);
        jScrollPane1.setViewportView(panelPQR);

        reportUser.setBackground(new java.awt.Color(252, 252, 252));
        reportUser.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        reportUser.setText("Reportar Usuario");
        reportUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportUserActionPerformed(evt);
            }
        });

        sendPDF.setBackground(new java.awt.Color(252, 252, 252));
        sendPDF.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sendPDF.setText("Enviar PDF");

        pqrType.setEditable(false);
        pqrType.setBackground(new java.awt.Color(252, 252, 252));
        pqrType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de PQR:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(reportUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(sendPDF)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pqrType)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(pqrType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportUser)
                    .addComponent(sendPDF))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportUserActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_reportUserActionPerformed

	public void mensajepanel(String text) // imprime un mensaje de texto en el
		// textArea de la interfaz.
	{
		panelPQR.append(text);
	}

	public File getFile() /*obtiene un archivo del explorador (usado para el pdf)*/
	{
		JFileChooser fc = new JFileChooser(
			System.getProperty("user.dir"));
		fc.showOpenDialog(fc);
		return fc.getSelectedFile();
	}
	
	public void Mensajes(String i) /*Muestra un mensaje en pantalla*/
	{
		JOptionPane.showMessageDialog(null, i);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea panelPQR;
    public javax.swing.JTextField pqrType;
    public javax.swing.JButton reportUser;
    public javax.swing.JButton sendPDF;
    // End of variables declaration//GEN-END:variables
}
